[project]
name = "littlelemon"
version = "0.1.0"
description = "Meta Capstone Project: Little Lemon Restaurant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "mysqlclient>=2.2.7",
]
